### ISSUE TITLE
Terraform Orb - Allow multiple var_file parameters

### ISSUE THREAD

**Issue by steinybot** [ovotech/circleci-orbs#107]
Terraform permits passing multiple `-var-file` parameters and so the orb should too:
```
❯ terraform plan -var-file=cicd.tfvars -var-file=terraform.tfvars
Refreshing Terraform state in-memory prior to plan...
```

This is related to https://github.com/ovotech/circleci-orbs/issues/106 in that either that issue or this issue is required in order to overcome the limitation in https://github.com/hashicorp/terraform/issues/16197.

**Comment by danielflookovo** [comment]
CircleCI doesn't support passing multiple parameters with the same name, they are restricted by the YAML format in that respect. 

You can achieve this in the Terraform Orb by passing a single `var_file` (or `var`/`backend_config`/`backend_config_file`) with a comma separated value. e.g.:

```yaml
jobs:
  terraform_plan:
    executor: terraform/terraform-0_12
    steps:
    - checkout
    - terraform/plan:
        path: terraform/deployments/cluster
        workspace: gauges-uat
        var_file: env/nonprod.tfvars,env/common.tfvars
```
