### ISSUE TITLE
Clair JSON report artifact path

### ISSUE THREAD

**Issue by skjolber** [ovotech/circleci-orbs#19]
The default output path does not work.

`Could not create a report: could not write to file open /<repo>/<project>/<repo>:<tag>.json: no such file or directory
`

Support the 

-r, --report=""

parameter in

https://github.com/arminc/clair-scanner

**Comment by danielflookovo** [comment]
It works for me. Do you have a circleci config and logs you can share?

**Comment by skjolber** [comment]
Hi, we're not doing to much fancy, but we are using a private repository. 

```
jobs:
  container_vulnerability_scan:
    executor: clair/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: *gcp-docker-login
      - clair/scan:
          image_file: "./gcr.image.version"
```

where the ./gcr.image.version contains the full `/<repo>/<project>/<repo>:<tag>`. The default file path is really not a path that would normally be available in a normal linux installation - where does the report go in your testing?
