### ISSUE TITLE
ovotech/ssh-proxy@1.0.0 issue

### ISSUE THREAD

**Issue by vallard** [ovotech/circleci-orbs#222]
I love the idea of using ssh-proxy in my builds.  I saw way down below in the source the requirement for this to be run on a machine but I'm still having issues making it work.  Do you have an example `.circleci/config.yml` that shows how this orb can work?  Specifically I'm looking to call it using AWS-EKS.  Thanks for any help and thank you for putting this orb together.

**Comment by vallard** [comment]
Ah, I figured it out: 
```
version: 2.1
orbs:
  ssh-proxy: ovotech/ssh-proxy@1.0.0
...
deploy-application:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - ssh-proxy/proxy-up:
            hostname: myhost
            port: 22
            username: user01
            private_key_fingerprint: 13:xx:xx:xx:...:00
            routed_network_cidrs: 10.49.0.0/16
            connection_test_host: 10.49.0.33
            connection_test_port: 22
...
```

Thanks again for publishing this!
