### ISSUE TITLE
terraform/default executor: Refreshing state included in plan 

### ISSUE THREAD

**Issue by Mongey** [ovotech/circleci-orbs#300]
👋 I updated to from the  `ovotech/terraform` orb to ` ovotech/terraform-v2`, using the `terraform/default` executor and the GitHub comments include lots of `Refreshing state...` output.

Also updating from terraform `0.14.3` to `0.15.3`

`.circleci/config`
```yml
version: 2.1

 orbs:
   terraform: ovotech/terraform-v2@2

  terraform_plan:
     executor: terraform/default
     steps:
       - checkout
       - terraform/plan:
          path: global
          var_file: global/terraform.auto.tfvars
```

`comment`
```
module.foo.random_password.admin: Refreshing state... [id=none]
module.bar: Refreshing state... [id=mIyRmJ9aQcFJs_aB2Q]
module.baz: Refreshing state... [id=none]
...
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.foo.aws_db_instance.db will be updated in-place
  ~ resource "aws_db_instance" "db" {
      + domain                                = ""
      + domain_iam_role_name                  = ""
        id                                    = "foobar-20210322203922772700000004"
        name                                  = "foobar"
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ password                              = (sensitive value)
      + performance_insights_kms_key_id       = ""
      + replicate_source_db                   = ""
      + timezone                              = ""
        # (47 unchanged attributes hidden)
    }
```

I do think that compact_plan is being used: here's some output from the bash script.

```
+ TFMASK=tfmask
+ hash tfmask
+ TFMASK=cat
+ COMPACT_PLAN=compact_plan
+ hash compact_plan
```
