### ISSUE TITLE
optionally specify fmt-check step name

### ISSUE THREAD

**Issue by mishabruml** [ovotech/circleci-orbs#500]
https://github.com/ovotech/circleci-orbs/blob/c4634f4eaaba054ed99ecff0b34a9e63d89c477f/terraform-v2/orb.yml#L313

I'm using `fmt-check` like this
```yml
jobs:
  terraform_fmt:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt-check:
          path: terraform/environments/non-production
          name: fmt non-production
      - terraform/fmt-check:
          path: terraform/environments/production
          name: fmt production
```

Which results in circleci looking like this 
![image](https://user-images.githubusercontent.com/25983780/204536452-2f06bc6c-b67f-4d2a-baa2-7c41fe815ab3.png)

If the `name` property could be specified, then the step names would be more meaningful. Perhaps they could default to a concat with the tf path? e.g. `name: "terraform fmt ${*path}"`
